version: '2.1'
services:
  testdb:
    container_name: testdb
    image: frickt/testdb:1.0.1
    shm_size: 1g
    volumes:
      - /Users/thomasfrick/docker/oracle11202/home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
    environment:
      - ORACLE_PWD=TIE2002sys
